export const SKILL_LOADING = 'SKILL_LOADING';
export const SKILL_ABORT = 'SKILL_ABORT';

export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';
export const INSERT_SKILL_SUCCESS = 'INSERT_SKILL_SUCCESS';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';

export const LOGOUT_SKILL = 'LOGOUT_SKILL';