version: "3.8"

services:
  frontend:
    stdin_open: true
    build:
        context: ./frontend
    ports:
      - "5001:3000"
    volumes:
      - "/app/node_modules"
      - "/home/maya/Udvikling/Docker/laravel-doctrine-migrations-2.2/frontend/src:/app"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "5002:80"
    volumes:
      - '/home/maya/Udvikling/Docker/laravel-doctrine-migrations-2.2/backend/src:/var/www/html/'
    read_only: false
    depends_on:
      - database
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5003:80
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: wM09y6Rre
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wM09y6Rre
      MYSQL_DATABASE: laravel
    volumes:
      - "/home/maya/Udvikling/Docker/laravel-doctrine-migrations-2.2/database/data:/var/lib/mysql"
