version: "3"
services:
  frontend:
    stdin_open: true
    build:
        context: ./frontend
    image: job-finder-frontend
    ports:
      - "5001:3000"
    volumes:
      - "/app/node_modules"
      - ./frontend/src:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    image: job-finder-backend
    ports:
      - "5002:80"
    volumes:
      - ./backend/src:/var/www/html
    read_only: false
    depends_on:
      - database
    environment: 
      APP_URL: http://localhost
      APP_NAME: "Job Finder"
      APP_ENV: local
      APP_KEY: nIUYRvYsDIGMFJaunZpE0U4nDSgXmruD
      LOG_CHANNEL: stack
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      JWT_SECRET: Ir23rabwhdQK6kFCjc8ly82ZBQxBScn1aNOZSSkNYPtBH9SOqCm6T73JQjaQ4qOP
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD : wM09y6Rre
  phpmyadmin:
    image: phpmyadmin:5.0.2-apache
    restart: always
    ports:
      - 5003:80
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: wM09y6Rre
  database:
    image: mariadb:10.5.5-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wM09y6Rre
      MYSQL_DATABASE: laravel
    volumes:
      - ./database/data:/var/lib/mysql