
export const USER_LOADING = 'USER_LOADING';
export const USER_ABORT = 'USER_ABORT';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_POSTING_SUCCESS';