<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JobExperience extends \App\Entities\JobExperience implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'jobTitle', 'employer', 'startedDate', 'endedDate', 'createdTime', 'updatedTime', 'performedTasks', 'givenTestimonials', 'ownerUser'];
        }

        return ['__isInitialized__', 'id', 'jobTitle', 'employer', 'startedDate', 'endedDate', 'createdTime', 'updatedTime', 'performedTasks', 'givenTestimonials', 'ownerUser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (JobExperience $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getJobTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobTitle', []);

        return parent::getJobTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobTitle($jobTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobTitle', [$jobTitle]);

        return parent::setJobTitle($jobTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployer', []);

        return parent::getEmployer();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployer($employer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployer', [$employer]);

        return parent::setEmployer($employer);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartedDate', []);

        return parent::getStartedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartedDate($startedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartedDate', [$startedDate]);

        return parent::setStartedDate($startedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndedDate', []);

        return parent::getEndedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndedDate($endedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndedDate', [$endedDate]);

        return parent::setEndedDate($endedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnerUser', []);

        return parent::getOwnerUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnerUser(\App\Entities\User $ownerUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnerUser', [$ownerUser]);

        return parent::setOwnerUser($ownerUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedTime', []);

        return parent::getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedTime($createdTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedTime', [$createdTime]);

        return parent::setCreatedTime($createdTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedTime', []);

        return parent::getUpdatedTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedTime($updatedTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedTime', [$updatedTime]);

        return parent::setUpdatedTime($updatedTime);
    }

    /**
     * {@inheritDoc}
     */
    public function addTask(\App\Entities\Task $task)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTask', [$task]);

        return parent::addTask($task);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTask(\App\Entities\Task $task)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTask', [$task]);

        return parent::removeTask($task);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerformedTasks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerformedTasks', []);

        return parent::getPerformedTasks();
    }

    /**
     * {@inheritDoc}
     */
    public function removeTasks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTasks', []);

        return parent::removeTasks();
    }

}
