export const LOAD_POSTINGS_LOADING = 'LOAD_POSTINGS_LOADING';
export const LOAD_POSTINGS_SUCCESS = 'LOAD_POSTINGS_SUCCESS';
export const LOAD_POSTINGS_ERROR = 'LOAD_POSTINGS_ERROR';

export const INSERT_POSTING_LOADING = 'INSERT_POSTING_LOADING';
export const INSERT_POSTING_SUCCESS = 'INSERT_POSTING_SUCCESS';
export const INSERT_POSTING_ERROR = 'INSERT_POSTING_ERROR';

export const UPDATE_POSTING_LOADING = 'UPDATE_POSTING_LOADING';
export const UPDATE_POSTING_SUCCESS = 'UPDATE_POSTING_SUCCESS';
export const UPDATE_POSTING_ERROR = 'UPDATE_POSTING_ERROR';

export const DELETE_POSTING_LOADING = 'DELETE_POSTING_LOADING';
export const DELETE_POSTING_SUCCESS = 'DELETE_POSTING_SUCCESS';
export const DELETE_POSTING_ERROR = 'DELETE_POSTING_ERROR';

export const LOGOUT_POSTING = 'LOGOUT_POSTING';