export const POSTING_LOADING = 'POSTING_LOADING';
export const POSTING_ABORT = 'POSTING_ABORT';

export const LOAD_POSTINGS_SUCCESS = 'LOAD_POSTINGS_SUCCESS';
export const INSERT_POSTING_SUCCESS = 'INSERT_POSTING_SUCCESS';
export const UPDATE_POSTING_SUCCESS = 'UPDATE_POSTING_SUCCESS';
export const DELETE_POSTING_SUCCESS = 'DELETE_POSTING_SUCCESS';

export const LOGOUT_POSTING = 'LOGOUT_POSTING';